"use strict";
const KEY="SITIN_EMPIRE_SAVE_V1";
const S={money:1000,oil:500,industry:100,income:50,army:{infantry:600,armor:250,air:100,navy:50},selected:null,turn:1,purchases:[],statements:[],news:["بازی آغاز شد؛ وضعیت جهان زیر نظر SITIN است."]};
const C=[{id:"sitin",n:"SITIN",f:"🇸🇮",x:.50,y:.46,p:100,c:0x4f8cff},{id:"aurora",n:"AURORA",f:"🌐",x:.34,y:.30,p:82,c:0x55d6be},{id:"vortex",n:"VORTEX",f:"🛰️",x:.67,y:.29,p:91,c:0xf39a65},{id:"usa",n:"USA",f:"🇺🇸",x:.21,y:.48,p:96,c:0x6da8ff},{id:"orion",n:"ORION",f:"🌙",x:.75,y:.52,p:74,c:0xd083ff},{id:"terra",n:"TERRA",f:"🌍",x:.57,y:.70,p:88,c:0x79cf73}];
const SHOP=[['ذخیره آهن','⛏️',120,20],['محموله نفت','🛢️',180,30],['قطعات صنعتی','⚙️',250,25],['واحد نیروی زمینی','🪖',120,30],['واحد زرهی','🛡️',300,8],['واحد هوایی','✈️',420,4],['واحد دریایی','🚢',500,3]];
const $=id=>document.getElementById(id);let game,markers=[];
function toast(t){let e=$("toast");e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function render(){["money","oil","industry","income"].forEach(k=>$(k).textContent=Math.floor(S[k]));Object.keys(S.army).forEach(k=>$(k).textContent=Math.floor(S.army[k]));$("news").innerHTML=S.news.slice(-4).reverse().map(x=>`<div class="news-item">${x}</div>`).join('');}
function countriesUI(){ $("countries").innerHTML=C.map(c=>`<div class="country ${S.selected===c.id?'active':''}" data-c="${c.id}"><b>${c.f} ${c.n}</b><small>قدرت راهبردی: ${c.p}</small></div>`).join('');document.querySelectorAll('[data-c]').forEach(e=>e.onclick=()=>select(e.dataset.c)); }
function shopUI(){ $("shop").innerHTML=SHOP.map((x,i)=>`<button data-shop="${i}">${x[1]} ${x[0]} — $${x[2]}</button>`).join('');document.querySelectorAll('[data-shop]').forEach(e=>e.onclick=()=>buy(+e.dataset.shop)); }
function select(id){S.selected=id;let c=C.find(x=>x.id===id);let minister=id==='sitin'?'وزیر امور داخلی':'وزیر امور خارجه';$("statement").innerHTML=`<b>${minister}</b><br>موضوع: روابط و وضعیت ${c.n}<br><span>آماده صدور بیانیه رسمی.</span>`;countriesUI();markers.forEach(m=>m.setScale(m.country.id===id?1.3:1));}
function buy(i){let x=SHOP[i];if(S.money<x[2]){toast('بودجه کافی نیست');return}S.money-=x[2];S.purchases.push({item:x[0],cost:x[2],turn:S.turn});if(x[0].includes('نفت'))S.oil+=x[3];else if(x[0].includes('آهن'))S.industry+=x[3];else if(x[0].includes('قطعات'))S.industry+=x[3];else if(x[0].includes('زمینی'))S.army.infantry+=x[3];else if(x[0].includes('زرهی'))S.army.armor+=x[3];else if(x[0].includes('هوایی'))S.army.air+=x[3];else if(x[0].includes('دریایی'))S.army.navy+=x[3];S.news.push(`خرید ثبت شد: ${x[0]} برای $${x[2]}.`);render();toast('خرید با موفقیت ثبت شد ✓')}
function act(a){if(a==='train'){if(S.money<80)return toast('بودجه کافی نیست');S.money-=80;S.army.infantry+=40;S.industry+=1;S.news.push('۴۰ نیروی جدید آموزش دیدند.')}if(a==='industry'){if(S.money<150)return toast('بودجه کافی نیست');S.money-=150;S.industry+=8;S.income+=5;S.news.push('صنعت ملی توسعه یافت و درآمد دوره‌ای افزایش پیدا کرد.')}if(a==='mission'){if(S.oil<40)return toast('نفت کافی نیست');S.oil-=40;S.money+=120;S.news.push('مأموریت ملی با موفقیت انجام شد؛ +$120.')}if(a==='service'){if(S.money<100)return toast('بودجه کافی نیست');S.money-=100;S.industry+=2;S.news.push('برنامه خدمات عمومی اجرا شد؛ رضایت داخلی افزایش یافت.')}render()}
function statement(){let c=C.find(x=>x.id===S.selected)||C[0];let minister=c.id==='sitin'?'وزیر امور داخلی':'وزیر امور خارجه';let subject=c.id==='sitin'?'توسعه و ثبات داخلی':`روابط با ${c.n}`;let text=`به نام دولت SITIN، در چارچوب منافع ملی و حفظ ثبات منطقه‌ای، موضع رسمی کشور درباره «${subject}» اعلام می‌شود. دولت بر گفت‌وگو، آمادگی و تأمین منافع مردم تأکید دارد.`;S.statements.push({minister,subject,text,turn:S.turn});$("statement").innerHTML=`<b>${minister}</b><br>${text}<br><small>دوره ${S.turn}</small>`;S.news.push(`بیانیه رسمی توسط ${minister} درباره ${subject} صادر شد.`);render();toast('بیانیه رسمی صادر شد 📜')}
function save(){localStorage.setItem(KEY,JSON.stringify(S));toast('ذخیره شد ✓')}
function load(){let x=localStorage.getItem(KEY);if(!x)return toast('ذخیره‌ای وجود ندارد');Object.assign(S,JSON.parse(x));render();countriesUI();toast('بازی بارگذاری شد ✓')}
function nextTurn(){S.turn++;S.money+=S.income;S.oil+=5;S.news.push(`دوره ${S.turn}: درآمد +$${S.income} و نفت +5 دریافت شد.`);render();toast(`دوره ${S.turn} آغاز شد`)}
function boot(){game=new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#071624',scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},scene:{create}})}
function create(){let sc=this;drawMap(sc);drawMarkers(sc);sc.scale.on('resize',()=>{sc.children.removeAll();drawMap(sc);drawMarkers(sc)});}
function drawMap(sc){let w=sc.scale.width,h=sc.scale.height,g=sc.add.graphics();g.fillStyle(0x071624,1).fillRect(0,0,w,h);let land=[[[.07,.25],[.17,.18],[.31,.23],[.34,.38],[.23,.48],[.10,.42]],[[.38,.16],[.57,.11],[.69,.20],[.65,.34],[.52,.38],[.42,.30]],[[.71,.18],[.91,.23],[.96,.40],[.83,.47],[.72,.38]],[[.40,.45],[.55,.43],[.61,.59],[.57,.78],[.46,.86],[.37,.66]],[[.66,.51],[.82,.49],[.91,.65],[.81,.80],[.69,.72]]];land.forEach((p,i)=>{g.fillStyle([0x12334a,0x173b4d,0x183747,0x14384f,0x17394a][i],1);g.beginPath();p.forEach((q,j)=>j?g.lineTo(q[0]*w,q[1]*h):g.moveTo(q[0]*w,q[1]*h));g.closePath();g.fillPath();g.lineStyle(1,0x2c5268,.8);g.strokePath()});for(let x=0;x<w;x+=65){g.lineStyle(1,0x173247,.3);g.lineBetween(x,0,x,h)}for(let y=0;y<h;y+=65){g.lineStyle(1,0x173247,.3);g.lineBetween(0,y,w,y)}}
function drawMarkers(sc){markers=[];let w=sc.scale.width,h=sc.scale.height;C.forEach(c=>{let q=sc.add.container(c.x*w,c.y*h);q.country=c;q.setSize(54,54).setInteractive(new Phaser.Geom.Circle(0,0,27),Phaser.Geom.Circle.Contains);let glow=sc.add.circle(0,0,27,c.c,.12),ring=sc.add.circle(0,0,21,0,0);ring.setStrokeStyle(2,c.c,.8);let dot=sc.add.circle(0,0,15,c.c,1),label=sc.add.text(0,30,c.n,{fontFamily:'Tahoma,Arial',fontSize:'12px',fontStyle:'bold',color:'#eef5ff'}).setOrigin(.5,0);q.add([glow,ring,dot,label]);q.on('pointerdown',()=>select(c.id));sc.tweens.add({targets:glow,scale:1.25,alpha:.03,duration:1200,yoyo:true,repeat:-1});markers.push(q)})}
document.addEventListener('DOMContentLoaded',()=>{render();countriesUI();shopUI();boot();$('save').onclick=save;$('load').onclick=load;$('issue').onclick=statement;document.querySelectorAll('[data-a]').forEach(e=>e.onclick=()=>act(e.dataset.a));setInterval(nextTurn,30000);let b=document.createElement('button');b.textContent='⏭️ پایان دوره';b.onclick=nextTurn;$('news').parentElement.insertBefore(b,$('news'));});